import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import ts from 'typescript';
const require=createRequire(import.meta.url),cache=new Map();
function load(file){file=path.resolve(file);if(cache.has(file))return cache.get(file);if(file.endsWith('.json'))return JSON.parse(fs.readFileSync(file,'utf8'));const output=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;const module={exports:{}};new Function('require','module','exports',output)(id=>id.startsWith('@/')?load(path.resolve(id.slice(2))):id.startsWith('.')?load(path.resolve(path.dirname(file),id+'.ts')):require(id),module,module.exports);cache.set(file,module.exports);return module.exports;}
const d=load('lib/data.ts'),r=load('lib/reporting.ts');
assert.equal(d.tasks.length,95);assert.equal(d.standards.length,299);assert.equal(d.indicators.length,43);assert.equal(d.accounts.length,32);assert.equal(load('data/systems.json').length,31);
for(const collection of [d.tasks,d.standards,d.indicators])assert.equal(new Set(collection.map(x=>x.id)).size,collection.length,'IDs must be unique');
assert.equal(new Set(d.tasks.map(t=>t.leadDepartmentName)).size,24);
for(const s of d.standards)assert.ok(d.tasks.some(t=>t.id===s.taskId),s.id+' refers to missing task');
for(const t of d.tasks)for(const id of t.linkedIndicatorIds)assert.ok(d.indicators.some(i=>i.id===id),t.id+' refers to missing indicator');
assert.equal(d.tasks.filter(d.taskOverdue).length,6);
const annualCounts=d.years.map(y=>d.standards.filter(s=>d.scheduled(s,y)).length);
assert.deepEqual(annualCounts,[132,117,98,55,77]);
assert.equal(d.average(d.tasks.map(t=>d.yearlyProgress(t,2026))),89);
const annual=d.standards.filter(s=>d.scheduled(s,2026));assert.equal(d.average(annual.map(s=>d.yearlyProgress(d.tasks.find(t=>t.id===s.taskId),2026))),88);
const strategy=d.accounts.find(a=>a.role==='strategy'),department=d.accounts.find(a=>a.username==='222gsywb');assert.equal(d.visibleTasks(strategy).length,95);assert.ok(d.visibleTasks(department).length<95);assert.ok(d.visibleTasks(department).every(t=>t.leadDepartmentId===department.departmentId||t.supportingDepartmentIds.includes(department.departmentId)));
const metric=d.standards.find(s=>s.id==='gs01-std-1'),target=d.targetFor(metric,2026);
const zero=r.parseReport({value:'0',text:'',progress:'',note:''},true,'gsywb');assert.equal(zero.value,0);assert.equal(r.reportProgress(metric,zero,2026),0);
assert.equal(r.reportProgress(metric,{...zero,value:target},2026),100);
assert.equal(r.reportProgress({...metric,achievementMode:'atMost'},{...zero,value:0},2026),100);
assert.throws(()=>r.parseReport({value:'',text:'',progress:'',note:''},true,'gsywb'));
assert.throws(()=>r.parseReport({value:'-1',text:'',progress:'',note:''},true,'gsywb'));
assert.throws(()=>r.parseReport({value:'NaN',text:'',progress:'',note:''},true,'gsywb'));
assert.throws(()=>r.parseReport({value:'',text:'完成',progress:'101',note:''},false,'gsywb'));
const milestone=r.parseReport({value:'',text:'完成方案评审',progress:'80',note:'待发布'},false,'gsywb');assert.equal(milestone.progress,80);
assert.notEqual(r.reportKey(metric.id,2026,'gsywb'),r.reportKey(metric.id,2027,'gsywb'));assert.notEqual(r.reportKey(metric.id,2026,'gsywb'),r.reportKey(metric.id,2026,'grywb'));
if(fs.existsSync('../reference/literal-arrays.json')){const source=JSON.parse(fs.readFileSync('../reference/literal-arrays.json','utf8'));for(const [file,key] of Object.entries({tasks:'lre',indicators:'hi',standards:'Jte',accounts:'c0'}))assert.deepEqual(load(`data/${file}.json`),source[key],file+' data differs from original DEMO');}
console.log('PASS: original data parity; IDs and relations; annual counts; demo progress; department visibility; report validation; zero and reverse targets; year/department isolation.');
console.log(JSON.stringify({tasks:95,standards:299,indicators:43,departments:24,systems:31,accounts:32,annualCounts,cockpitProgress:89,annualProgress:88}));
